/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Comment: typeof import('./src/components/content/playlist-detail/comment.vue')['default']
    Comments: typeof import('./src/components/content/playlist-detail/comments.vue')['default']
    Discovery: typeof import('./src/components/content/discovery/index.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCarousel: typeof import('element-plus/es')['ElCarousel']
    ElCarouselItem: typeof import('element-plus/es')['ElCarouselItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    Header: typeof import('./src/components/layout/header.vue')['default']
    LatestMv: typeof import('./src/components/content/latest-mv.vue')['default']
    Layout: typeof import('./src/components/layout/index.vue')['default']
    Menu: typeof import('./src/components/menu/index.vue')['default']
    MiniPlayer: typeof import('./src/components/mini-player/index.vue')['default']
    Mvs: typeof import('./src/components/content/discovery/mvs.vue')['default']
    PlaylistDetail: typeof import('./src/components/content/playlist-detail/index.vue')['default']
    Playlists: typeof import('./src/components/content/discovery/playlists.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Search: typeof import('./src/components/common/search.vue')['default']
    Songs: typeof import('./src/components/content/discovery/songs.vue')['default']
    Swipper: typeof import('./src/components/content/discovery/swipper.vue')['default']
  }
}
